# Generated by Django 4.2.3 on 2023-10-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_title", models.CharField(max_length=100)),
                ("service_desc", models.CharField(max_length=400)),
            ],
        ),
    ]
