# Generated by Django 4.2.3 on 2023-11-04 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appoffin", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Details",
            new_name="Service",
        ),
    ]
