# Generated by Django 4.2.3 on 2023-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appoffin", "0002_rename_details_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="logos",
            field=models.ImageField(default="", upload_to="finance/services_logos"),
        ),
    ]
