# Generated by Django 4.2.3 on 2024-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appoffin", "0003_service_logos"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("u_fname", models.CharField(max_length=23)),
                ("u_lname", models.CharField(max_length=23)),
                ("u_email", models.EmailField(max_length=254, unique=True)),
                ("u_mob", models.IntegerField()),
                ("u_pass", models.IntegerField()),
            ],
        ),
    ]
