# Generated by Django 4.2.3 on 2024-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appoffin", "0004_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
