# Generated by Django 4.2.3 on 2024-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appoffin", "0005_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="u_pass",
            field=models.CharField(max_length=23),
        ),
    ]
