# Generated by Django 4.2.3 on 2023-12-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_title", models.CharField(max_length=100)),
                ("package_desc", models.CharField(max_length=400)),
                (
                    "logos",
                    models.ImageField(default="", upload_to="packages/packages_logos"),
                ),
            ],
        ),
    ]
